# Generated by Django 2.1.5 on 2019-03-10 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteuser',
            name='date_of_birth',
            field=models.CharField(max_length=10, verbose_name='Date of birth'),
        ),
    ]
