# Generated by Django 2.1.5 on 2019-03-10 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0002_auto_20190310_1712'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteuser',
            name='reset_token',
            field=models.CharField(default=123456789, max_length=255, verbose_name='Token Used ro reset'),
            preserve_default=False,
        ),
    ]
