# Generated by Django 2.1.5 on 2019-03-11 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0004_auto_20190310_2136'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteuser',
            name='is_superuser',
        ),
    ]
