# Generated by Django 2.1.5 on 2019-03-11 02:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0006_auto_20190310_2228'),
    ]

    operations = [
        migrations.RenameField(
            model_name='siteuser',
            old_name='admin',
            new_name='is_admin',
        ),
        migrations.RemoveField(
            model_name='siteuser',
            name='active',
        ),
        migrations.RemoveField(
            model_name='siteuser',
            name='join_date',
        ),
        migrations.RemoveField(
            model_name='siteuser',
            name='staff',
        ),
        migrations.AddField(
            model_name='siteuser',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Date User joined'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='siteuser',
            name='reset_token',
            field=models.CharField(max_length=255, verbose_name='Reset Token'),
        ),
    ]
