# Generated by Django 2.1.5 on 2019-03-11 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0007_auto_20190310_2236'),
    ]

    operations = [
        migrations.RenameField(
            model_name='siteuser',
            old_name='is_admin',
            new_name='admin',
        ),
        migrations.AddField(
            model_name='siteuser',
            name='active',
            field=models.BooleanField(default=False, verbose_name='User is active'),
        ),
        migrations.AddField(
            model_name='siteuser',
            name='staff',
            field=models.BooleanField(default=False, verbose_name='User is staff'),
        ),
    ]
